### ISSUE TITLE
Extension appears to be loaded twice

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#37]
Whenever I get tracebacks from errors, I always seem to get the same trace twice.
Is the extension not being loaded properly? Something might be repeating in an unwanted way.

**Example**

```
Using binary at '/usr/bin/firefox'.
Using profile at '/tmp/tmpPAV9Fh.mozrunner'.
error: An exception occurred.
Traceback (most recent call last):
  File "chrome://browser/content/browser.js", line 5215, in delayedStartu
    .init(window);
  File "resource:///components/nsSessionStore.js", line 440, in sss_ini
    this.onLoad(aWindow);
  File "resource:///components/nsSessionStore.js", line 627, in sss_onLoa
    Services.obs.notifyObservers(null, NOTIFY_WINDOWS_RESTORED, "");
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/system/events.js", line 58, in 
    data: data
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/addon/runner.js", line 57, in 
    startup(null, options);
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/addon/runner.js", line 84, in startu
    let program = load(loader, loader.main).exports;
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/cuddlefish.js", line 177, in loa
    evaluate(sandbox, module.uri);
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/cuddlefish.js", line 142, in evaluat
    : scriptLoader.loadSubScript(uri, sandbox, encoding);
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/hashmask/lib/main.js", line 6, in 
    var sjcl = require(self.data.url("sjcl.js"));
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/cuddlefish.js", line 207, in requir
    base + " has no authority to load: " + id);
Error: Module: main located at hashmask/lib/main.js has no authority to load: resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/hashmask/data/sjcl.js
error: An exception occurred.
Traceback (most recent call last):
  File "chrome://browser/content/browser.js", line 5215, in delayedStartu
    .init(window);
  File "resource:///components/nsSessionStore.js", line 440, in sss_ini
    this.onLoad(aWindow);
  File "resource:///components/nsSessionStore.js", line 627, in sss_onLoa
    Services.obs.notifyObservers(null, NOTIFY_WINDOWS_RESTORED, "");
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/system/events.js", line 58, in 
    data: data
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/addon/runner.js", line 57, in 
    startup(null, options);
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/addon/runner.js", line 84, in startu
    let program = load(loader, loader.main).exports;
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/cuddlefish.js", line 177, in loa
    evaluate(sandbox, module.uri);
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/cuddlefish.js", line 142, in evaluat
    : scriptLoader.loadSubScript(uri, sandbox, encoding);
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/hashmask/lib/main.js", line 6, in 
    var sjcl = require(self.data.url("sjcl.js"));
  File "resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/api-utils/lib/cuddlefish.js", line 207, in requir
    base + " has no authority to load: " + id);
Error: Module: main located at hashmask/lib/main.js has no authority to load: resource://hashmask-at-sse-dot-se-dot-rit-dot-edu/hashmask/data/sjcl.js
Total time: 44.292276 seconds
Program terminated successfully.
```

**Comment by wyantb** [comment]
Where do you get that trace from?  In any case, I don't see any evidence of this now after my work.

**Comment by nickserv** [comment]
Ah, you're right, you fixed it recently. Thanks.

**Comment by wyantb** [comment]
No, but seriously, where did you have that trace?  I was only about to see stuff in the Ctrl-Shift-J console.

**Comment by nickserv** [comment]
Oh, I used the Firefox addons SDK and ran "cfx run" via the command line. (You need the SDK environment loaded first.)
